export type Book = {
  // Required fields
  bookId: string;
  title: string;
  bookFormat: "hardcover" | "paperback" | "ebook" | "audiobook" | "other";
  forRent: boolean;
  priceSale: number;
  stockQuantity: number;
  reservedQuantity: number;
  slug: string;
  // Optional fields
  isActive?: boolean;
  forSale?: boolean;
  totalRatings?: number;
  totalReviews?: number;
  createdAt?: string;
  updatedAt?: string;
  subtitle?: string | null;
  description?: string | null;
  isbn13?: string | null;
  isbn10?: string | null;
  publicationDate?: string | null;
  publishedYear?: number | null;
  pageCount?: number | null;
  language?: string | null;
  coverImageUrl?: string | null;
  edition?: string | null;
  bookCondition?: string | null;
  dimensions?: string | null;
  weightGrams?: number | null;
  priceRentDaily?: number | null;
  priceRentWeekly?: number | null;
  priceRentMonthly?: number | null;
  averageRating?: number | null;
  publisherId?: string | null;
  ownerId?: string | null;
  primaryCategoryId?: string | null;
  searchKeywords?: string[] | null;
  createdBy?: string | null;
  lastModifiedBy?: string | null;
  deletedAt?: string | null;
  deletedBy?: string | null;
};
