INSERT INTO authors (first_name, last_name, biography, birth_date, nationality, website_url)
VALUES
('Abraham', 'Verghese', 'Ethiopian-American physician and author of *Cutting for Stone* and *The Covenant of Water*.', '1955-01-01', 'Ethiopian-American', 'https://www.abrahamverghese.com'),
('Alex', 'Aster', 'Colombian-American YA author best known for the Lightlark fantasy series.', '1990-01-01', 'American', 'https://www.alexaster.com'),
('Amie', 'Kaufman & Jay Kristoff', 'Amie Kaufman is an Australian co-author of science-fiction and fantasy with Jay Kristoff.', '1985-01-01', 'Australian', 'https://www.amiekaufmanjaykristoff.com'),
('Andy', 'Weir', 'American author of *The Martian*, a bestselling sci-fi novel.', '1972-01-01', 'American', 'https://www.andyweir.com'),
('Anthony', 'Doerr', 'American novelist, author of *All the Light We Cannot See*, winner of the Pulitzer Prize.', '1973-01-01', 'American', 'https://www.anthonydoerr.com'),
('Barbara', 'Kingsolver', 'American novelist known for *The Poisonwood Bible* and environmental activism.', '1955-01-01', 'American', 'https://www.barbarakingsolver.com'),
('Bonnie', 'Garmus', 'American author of *Lessons in Chemistry*, blending wit and feminist themes.', '1957-01-01', 'American', 'https://www.bonniegarmus.com'),
('C.L.', 'Polk', 'Canadian author of queer historical fantasy, including *Witchmark*.', '1970-01-01', 'Canadian', 'https://www.clpolk.com'),
('Carissa', 'Broadbent', 'Canadian-born, U.S.-based fantasy author of *A Night of Blacker Darkness*.', '1985-01-01', 'American', 'https://www.carissabroadbent.com'),
('Cassandra', 'Clare', 'American author of *The Mortal Instruments* urban fantasy series.', '1973-01-01', 'American', 'https://www.cassandraclare.com'),
('Chelsea', 'Abdullah', 'American-Kuwaiti author of The Stardust Thief, inspired by Arabic folklore.', '1989-01-01', 'American-Kuwaiti', 'https://www.chelseaabdullah.com'),
('Chimamanda', 'Ngozi Adichie', 'Nigerian novelist and essayist, author of *Americanah* and *Half of a Yellow Sun*.', '1977-01-01', 'Nigerian', 'https://www.chimamanda.com'),
('Claire', 'Keegan', 'Irish short story writer and novelist celebrated for *Foster* and *Small Things Like These*.', '1968-01-01', 'Irish', 'https://www.clairekeegan.com'),
('Colleen', 'Hoover', 'American bestselling author of romance and YA novels, including *It Ends With Us*.', '1979-01-01', 'American', 'https://www.colleenhoover.com'),
('Colson', 'Whitehead', 'American Pulitzer Prize–winning novelist of *The Underground Railroad* and *The Nickel Boys*.', '1969-01-01', 'American', 'https://www.colsonwhitehead.com'),
('Cormac', 'McCarthy', 'American author of *The Road* and *No Country for Old Men*, known for his sparse prose.', '1933-01-01', 'American', 'https://www.cormacmccarthy.com'),
('David', 'Mitchell', 'British novelist known for *Cloud Atlas* with interlinked narratives.', '1969-01-01', 'British', 'https://www.davidmitchell.com'),
('Delia', 'Owens', 'American author of the bestselling novel *Where the Crawdads Sing*.', '1949-01-01', 'American', 'https://www.deliaowens.com'),
('Donna', 'Tartt', 'American novelist, author of *The Goldfinch*, winner of the Pulitzer Prize.', '1963-01-01', 'American', 'https://www.donnatartt.com'),
('Eleanor', 'Catton', 'New Zealand novelist who won the Booker Prize for *The Luminaries*.', '1985-01-01', 'New Zealander', 'https://www.eleanorcatton.com'),
('Elena', 'Ferrante', 'Italian pseudonymous author of the Neapolitan Novels, known for *My Brilliant Friend*.', '1943-01-01', 'Italian', 'https://www.elenaferrante.com'),
('Emily', 'A. Duncan', 'American fantasy author of *Legacy of the Mercenary King*.', '1989-01-01', 'American', 'https://www.emilyaduncan.com'),
('Emily', 'Henry', 'American romance author of *Beach Read* and *People We Meet on Vacation.*', '1989-01-01', 'American', 'https://www.emilyhenry.com'),
('Emily', 'St. John Mandel', 'Canadian novelist best known for *Station Eleven*, exploring connection amid collapse.', '1979-01-01', 'Canadian', 'https://www.emilystjohnmandel.com'),
('Erin', 'Morgenstern', 'American author of *The Night Circus*, a gothic fantasy novel.', '1978-01-01', 'American', 'https://www.erinmorgenstern.com'),
('Gabrielle', 'Zevin', 'American author of *The Storied Life of A. J. Fikry* blending literary whimsy.', '1977-01-01', 'American', 'https://www.gabriellezevin.com'),
('George', 'Saunders', 'American short-story writer and novelist, winner of the Booker Prize for *Lincoln in the Bardo*.', '1958-01-01', 'American', 'https://www.georgesaunders.com'),
('Gillian', 'Flynn', 'American author of *Gone Girl*, known for dark psychological thrillers.', '1971-01-01', 'American', 'https://www.gillianflynn.com'),
('Hernan', 'Diaz', 'Argentine-American novelist of *Trust* and *In the Distance*.', '1973-01-01', 'Argentine-American', 'https://www.hernandiaz.com'),
('Hilary', 'Mantel', 'British historical novelist, twice Booker Prize winner for the Wolf Hall trilogy.', '1952-01-01', 'British', 'https://www.hilarymantel.com'),
('Ian', 'McEwan', 'British author of *Atonement* and *Enduring Love*, exploring human psychology.', '1948-01-01', 'British', 'https://www.ianmcewan.com'),
('Isabel', 'Wilkerson', 'American journalist and historian, author of *The Warmth of Other Suns*.', '1961-01-01', 'American', 'https://www.isabelwilkerson.com'),
('Jay', 'Kristoff', 'Australian author of YA fantasy such as *The Illuminae Files* and *Empire of the Vampire*.', '1973-01-01', 'Australian', 'https://www.jaykristoff.com'),
('Jeannette', 'Walls', 'American journalist and memoirist, author of *The Glass Castle*.', '1960-01-01', 'American', 'https://www.jeannettewalls.com'),
('Jenn', 'Lyons', 'American fantasy author of the *A Chorus of Dragons* series.', '1970-01-01', 'American', 'https://www.jennlyons.com'),
('Katee', 'Robert', 'American romance author known for paranormal and fantasy tropes.', '1985-01-01', 'American', 'https://www.kateerobert.com'),
('Kazuo', 'Ishiguro', 'British author and Nobel laureate, known for *The Remains of the Day*.', '1954-01-01', 'British', 'https://www.kazuoishiguro.com'),
('Leigh', 'Bardugo', 'American fantasy author of the Grishaverse series (e.g., *Shadow and Bone*).', '1975-01-01', 'American', 'https://www.leighbardugo.com'),
('Madeline', 'Miller', 'American classicist and author of *Circe* and *The Song of Achilles*.', '1978-01-01', 'American', 'https://www.madelinemiller.com'),
('Margaret', 'Atwood', 'Canadian author of *The Handmaid’s Tale*, blending speculative fiction and feminism.', '1939-01-01', 'Canadian', 'https://www.margaretatwood.com'),
('Matt', 'Haig', 'British author whose *The Midnight Library* explores life choices and regret.', '1975-01-01', 'British', 'https://www.matthaig.com'),
('Olivie', 'Blake', 'American author of dark academia fantasy, including *The Atlas Six*.', '1990-01-01', 'American', 'https://www.olivieblake.com'),
('Prince', 'Harry', 'British royal and author of memoir *Spare*.', '1984-01-01', 'British', 'https://www.princeharry.com'),
('R.F.', 'Kuang', 'American speculative author of *The Poppy War* trilogy.', '1996-01-01', 'American', 'https://www.rfkuang.com'),
('Rebecca', 'Yarros', 'American romance and fantasy author, known for her emotionally charged stories.', '1980-01-01', 'American', 'https://www.rebeccayarros.com'),
('Renée', 'Ahdieh', 'American author of *The Wrath & the Dawn*, blending Middle Eastern folklore and romance.', '1983-01-01', 'American', 'https://www.reneeahdieh.com'),
('Renée', 'Carlino', 'American author of contemporary romance and women’s fiction.', '1978-01-01', 'American', 'https://www.reneecarlino.com'),
('Richard', 'Powers', 'American novelist known for *The Overstory*, exploring ecology and humanity.', '1957-01-01', 'American', 'https://www.richardpowers.com'),
('Sally', 'Rooney', 'Irish author of *Normal People*, exploring modern relationships and class.', '1991-01-01', 'Irish', 'https://www.sallyrooney.com'),
('Samantha', 'Shannon', 'British author of *The Bone Season* and *The Priory of the Orange Tree* fantasies.', '1991-01-01', 'British', 'https://www.samanthashannon.com'),
('Sarah', 'J. Maas', 'American fantasy author of *Throne of Glass* and *A Court of Thorns and Roses*.', '1986-01-01', 'American', 'https://www.sarahjmaas.com'),
('Scarlett', 'St. Clair', 'American fantasy author known for the *Queen of Grimm* series.', '1988-01-01', 'American', 'https://www.scarlettstclair.com'),
('Shelby', 'Mahurin', 'American YA fantasy author of *Serpent & Dove*.', '1994-01-01', 'American', 'https://www.shelbymahurin.com'),
('Shelley', 'Parker-Chan', 'Australian author of *She Who Became the Sun*, a reimagined historical epic.', '1980-01-01', 'Australian', 'https://www.shelleyparkerchan.com'),
('Stephanie', 'Garber', 'American author of the Caraval series blending magic and romance.', '1985-01-01', 'American', 'https://www.stephaniegarber.com'),
('Sue', 'Lynn Tan', 'Malaysian author of contemporary fantasy celebrating Southeast Asian heritage.', '1980-01-01', 'Malaysian', 'https://www.suelynntan.com'),
('Sunyi', 'Dean', 'British fantasy author of *The Book Eaters*, mixing magical realism and gothic horror.', '1985-01-01', 'British', 'https://www.sunyidean.com'),
('Suzanne', 'Collins', 'American author of *The Hunger Games* trilogy.', '1962-01-01', 'American', 'https://www.suzannecollinsbooks.com'),
('TJ', 'Klune', 'American author of LGBTQ+ speculative fiction, including *The House in the Cerulean Sea*.', '1982-01-01', 'American', 'https://www.tjklune.com'),
('Tahereh', 'Mafi', 'American author of YA dystopian fiction like *Shatter Me*.', '1988-01-01', 'American', 'https://www.taherehbooks.com'),
('Taylor', 'Jenkins Reid', 'American novelist behind *Daisy Jones & The Six* and *The Seven Husbands of Evelyn Hugo*.', '1983-01-01', 'American', 'https://www.taylorjenkinsreid.com'),
('Tomi', 'Adeyemi', 'Nigerian-American YA author of *Children of Blood and Bone*.', '1993-01-01', 'Nigerian-American', 'https://www.tomibooks.com'),
('Tracy', 'Deonn', 'American author of *Legendborn*, a YA magical realism novel rooted in Black Arthurian lore.', '1980-01-01', 'American', 'https://www.tracydeonn.com'),
('Tricia', 'Levenseller', 'American YA fantasy author known for *Daughter of the Siren Queen*.', '1990-01-01', 'American', 'https://www.tricialevenseller.com'),
('V.E.', 'Schwab', 'American fantasy author of *Vicious* and *The Invisible Life of Addie LaRue*.', '1987-01-01', 'American', 'https://www.veschwab.com'),
('Veronica', 'Roth', 'American author of the *Divergent* trilogy.', '1988-01-01', 'American', 'https://www.veronicarothbooks.com'),
('Victoria', 'Aveyard', 'American YA author of *Red Queen*, blending fantasy and dystopia.', '1990-01-01', 'American', 'https://www.victoriaaveyard.com'),
('Xiran', 'Jay Zhao', 'Canadian author of *Iron Widow*, reimagining ancient Chinese history with sci-fi elements.', '1990-01-01', 'Canadian', 'https://www.xiranjayzhao.com');

