INSERT INTO publishers (publisher_name, description, founded_year, country, website_url, is_active)
VALUES
('Alfred A. Knopf', 'A prestigious American publishing house known for literary fiction, nonfiction, and translated works, Alfred A. Knopf has been a hallmark of quality since 1915.', 1915, 'USA', 'https://www.alfredaaknopf.com', true),
('Amulet Books', 'An imprint of Abrams Books, Amulet specializes in middle grade and young adult fiction, including bestselling illustrated series.', 1998, 'USA', 'https://www.amuletbooks.com', true),
('Atria Books', 'A division of Simon & Schuster, Atria publishes a wide range of fiction and nonfiction with an emphasis on strong storytelling and diverse voices.', 2002, 'USA', 'https://www.atriabooks.com', true),
('Atria/Emily Bestler Books', 'An Atria Books imprint led by Emily Bestler, this publisher focuses on high-quality commercial fiction and compelling nonfiction.', 2011, 'USA', 'https://www.atriaemilybestlerbooks.com', true),
('Ballantine Books', 'A major trade paperback and hardcover publisher under Penguin Random House, known for bestselling fiction, nonfiction, and genre titles.', 1952, 'USA', 'https://www.ballantinebooks.com', true),
('Berkley', 'An imprint of Penguin Random House, Berkley is known for romance, mystery, thrillers, and commercial women’s fiction.', 1955, 'USA', 'https://www.berkley.com', true),
('Bloomsbury Publishing', 'A British independent publisher best known for the Harry Potter series, Bloomsbury produces literary fiction, nonfiction, children’s, and academic works.', 1986, 'UK', 'https://www.bloomsbury.com', true),
('Crown Publishing Group', 'A division of Penguin Random House, Crown publishes award-winning nonfiction, memoirs, and commercial fiction.', 1933, 'USA', 'https://www.crownpublishinggroup.com', true),
('Del Rey', 'Specializing in science fiction and fantasy, Del Rey is a leading imprint under Penguin Random House with a legacy of genre-defining titles.', 1977, 'USA', 'https://www.delrey.com', true),
('Doubleday', 'One of America’s oldest publishers, Doubleday is known for bestselling fiction, narrative nonfiction, and influential classics.', 1897, 'USA', 'https://www.doubleday.com', true),
('Ecco', 'An imprint of HarperCollins, Ecco focuses on literary fiction, poetry, and high-quality nonfiction with a distinctive voice.', 1971, 'USA', 'https://www.ecco.com', true),
('Entangled: Red Tower Books', 'A fantasy-focused imprint of Entangled Publishing, Red Tower Books champions romantic fantasy and speculative fiction.', 2011, 'USA', 'https://www.entangledredtowerbooks.com', true),
('Europa Editions', 'An independent publisher based in Italy and New York, Europa Editions is known for literary fiction and international voices in translation.', 2005, 'Italy', 'https://www.europaeditions.com', true),
('Faber and Faber', 'A leading independent UK publisher, Faber and Faber is renowned for literary fiction, poetry, and award-winning nonfiction.', 1929, 'UK', 'https://www.faber.co.uk', true),
('Farrar, Straus and Giroux', 'A prestigious imprint of Macmillan, FSG is known for literary fiction, nonfiction, poetry, and Nobel Prize-winning authors.', 1946, 'USA', 'https://www.farrarstrausandgiroux.com', true),
('Feiwel & Friends', 'A children’s and young adult imprint of Macmillan, Feiwel & Friends publishes bestselling middle grade and teen novels.', 2006, 'USA', 'https://www.feiwelandfriends.com', true),
('Flatiron Books', 'An innovative imprint of Macmillan, Flatiron publishes high-quality literary and commercial fiction, nonfiction, and memoirs.', 2014, 'USA', 'https://www.flatironbooks.com', true),
('G.P. Putnam''s Sons', 'A respected American publisher known for bestselling thrillers, literary fiction, and nonfiction across genres.', 1838, 'USA', 'https://www.gpputnamsons.com', true),
('Grove Press', 'An influential independent publisher, Grove Press is known for groundbreaking literary fiction, political nonfiction, and drama.', 1947, 'USA', 'https://www.grovepress.com', true),
('Harper', 'Founded in 1817, Harper is one of the oldest US publishers, producing a broad range of literary fiction, nonfiction, and classics.', 1817, 'USA', 'https://www.harper.com', true),
('Harper Voyager', 'The science fiction and fantasy imprint of HarperCollins, Harper Voyager publishes top speculative fiction authors worldwide.', 1995, 'USA', 'https://www.harpervoyager.com', true),
('HarperCollins', 'One of the “Big Five” publishers, HarperCollins releases a vast catalog of fiction, nonfiction, children’s, and academic titles.', 1989, 'USA', 'https://www.harpercollins.com', true),
('HarperTeen', 'A young adult imprint of HarperCollins, HarperTeen publishes bestselling and award-winning teen novels across all genres.', 1992, 'USA', 'https://www.harperteen.com', true),
('Henry Holt Books for Young Readers', 'A children’s and YA imprint of Macmillan, publishing high-quality illustrated books and novels for young readers.', 1866, 'USA', 'https://www.henryholtbooksforyoungreaders.com', true),
('Henry Holt and Co.', 'A historic American publisher, Henry Holt and Co. produces literary fiction, nonfiction, and academic works.', 1866, 'USA', 'https://www.henryholtandco.com', true),
('Hogarth', 'A literary imprint of Penguin Random House, Hogarth focuses on bold, contemporary fiction with international appeal.', 2012, 'UK', 'https://www.hogarthbooks.com', true),
('Imprint', 'A children’s and YA imprint dedicated to publishing innovative, diverse, and engaging books across genres.', 2016, 'USA', 'https://www.imprint.com', true),
('Independently Published', 'A self-publishing designation for authors who release their work without a traditional publishing house.', 2000, 'USA', 'https://www.independentlypublished.com', true),
('Independently published', 'A self-publishing designation used by independent authors distributing their work digitally and in print.', 2000, 'USA', 'https://www.independentlypublished.com', true),
('Jonathan Cape', 'A literary imprint of Penguin Random House UK, Jonathan Cape is renowned for contemporary fiction, nonfiction, and graphic novels.', 1921, 'UK', 'https://www.jonathancape.com', true),
('Katherine Tegen Books', 'An imprint of HarperCollins specializing in young adult and middle grade fiction, often with strong emotional storytelling.', 2003, 'USA', 'https://www.katherinetegenbooks.com', true),
('Knopf', 'A distinguished American publisher within Penguin Random House, Knopf is known for award-winning literary fiction and nonfiction.', 1915, 'USA', 'https://www.knopf.com', true),
('Knopf Books for Young Readers', 'A children’s imprint of Knopf, publishing picture books, middle grade, and YA titles with literary merit.', 1915, 'USA', 'https://www.knopfbooksforyoungreaders.com', true),
('Little, Brown and Company', 'A major American publisher, Little, Brown releases acclaimed fiction, nonfiction, and children’s books.', 1837, 'USA', 'https://www.littlebrown.com', true),
('Margaret K. McElderry Books', 'An imprint of Simon & Schuster specializing in middle grade and young adult fiction, known for beloved fantasy and adventure series.', 1972, 'USA', 'https://www.margaretkmcelderrybooks.com', true),
('Montlake', 'An Amazon Publishing imprint focusing on romance and relationship-driven fiction.', 2011, 'USA', 'https://www.montlake.com', true),
('Nan A. Talese', 'A literary imprint of Doubleday, known for publishing distinguished fiction and nonfiction by acclaimed authors.', 1990, 'USA', 'https://www.nanatalese.com', true),
('Orbit', 'An international science fiction and fantasy publisher, Orbit is recognized for bestselling and award-winning genre fiction.', 1974, 'USA', 'https://www.orbitbooks.net', true),
('Penguin Teen', 'A Penguin Random House imprint for young adult fiction, featuring bestselling and diverse voices for teen readers.', 1984, 'USA', 'https://www.penguinteen.com', true),
('Putnam Juvenile', 'The children’s imprint of G.P. Putnam’s Sons, publishing middle grade and YA titles across genres.', 1838, 'USA', 'https://www.putnamjuvenile.com', true),
('Random House', 'One of the world’s largest publishers, Random House releases a vast array of fiction, nonfiction, and children’s books.', 1927, 'USA', 'https://www.randomhouse.com', true),
('Riverhead Books', 'An imprint of Penguin Random House, Riverhead is known for literary fiction, narrative nonfiction, and diverse global voices.', 1994, 'USA', 'https://www.riverheadbooks.com', true),
('Scholastic Press', 'The flagship imprint of Scholastic Inc., publishing bestselling children’s and YA books worldwide.', 1920, 'USA', 'https://www.scholasticpress.com', true),
('Scribner', 'A historic American publisher known for literary fiction, memoir, and works by classic authors like F. Scott Fitzgerald and Stephen King.', 1846, 'USA', 'https://www.scribner.com', true),
('Sourcebooks Casablanca', 'An imprint of Sourcebooks specializing in romance and women’s fiction with broad commercial appeal.', 1987, 'USA', 'https://www.sourcebookscasablanca.com', true),
('St. Martin''s Press', 'A major publisher under Macmillan, St. Martin’s Press offers bestselling fiction, nonfiction, and popular genre titles.', 1952, 'USA', 'https://www.stmartinspress.com', true),
('Tor Books', 'The premier science fiction and fantasy imprint of Macmillan, Tor Books publishes top genre authors and award winners.', 1980, 'USA', 'https://www.tor.com', true),
('Viking', 'An imprint of Penguin Random House, Viking is known for literary fiction, biography, and high-quality nonfiction.', 1935, 'USA', 'https://www.viking.com', true),
('W. W. Norton & Company', 'An independent, employee-owned publisher producing respected fiction, nonfiction, and academic works.', 1923, 'USA', 'https://www.wwnorton.com', true),
('William Morrow', 'An imprint of HarperCollins, William Morrow publishes commercial fiction, nonfiction, and memoir.', 1931, 'USA', 'https://www.williammorrow.com', true);

