name: Lint & Type Check
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint-and-typecheck:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Run lint
        run: bunx turbo run lint
      - name: Run type check
        run: bunx turbo run check-types
